all: fizzbuzz fib sum reverse frame 

fizzbuzz: fizzbuzz.cpp
	g++ fizzbuzz.cpp -o fizzbuzz

fib: fib.cpp
	g++ fib.cpp -o fib

sum: sum.cpp
	g++ sum.cpp -o sum

reverse: reverse.cpp
	g++ reverse.cpp -o reverse

frame: frame.cpp
	g++ frame.cpp -o frame
clean: 
	rm -f fizzbuzz sum reverse fib frame 
